name = "apk2source-api-v3"
main = "backend/worker.js"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
APK2SOURCE_REPO = "vladleopold/apk2source"
APK2SOURCE_SPINE_REPO = "vladleopold/source_spine"
APK2SOURCE_SOURCE_REPO = "vladleopold/game_source"
GITHUB_TOKEN = "kgh2.rJ1aWKi4o+K59ydXKCTAHA==:VARd/bn4lX6bOJQwJSICxQ==:JJ1wKGc//7CX1BndlBNnWI+eGZ+pKjD+aZX0F9AmXSfbF1+JTYXjwZO6IRhZ2VDWtuvCAEhJfJpubsNPlNBVDXOiKGd7/p8OgtPsWFDZhWCBqNEFHNOashDPTu19Y3BuvLZE2M+xTqpx78Pi6m+cDVTUDMMy67ZTDbxNAc0usZD52sRruNal7IZggXP08ve0YzILpKNF73R9RggOORlUqwPGXR+FvNtdSN69AaEcU6KkBBdWoD87FRVstnPLYMOy5MUjkmt2OVB16cLfbrHhnY3sO6yQgkOjVESfARZTIlW1Kd/MYoaA2X2Fk2U70SsMJMIxHoHaL7nK+7rOt8om7RYAAV/qWYi0YUr8hf9ms0e8K+Q3keSNld7+vdAxFNlur5ycygbZyWdqg4rAThMkr26wpGGayiEey0exVmE6PqGbTLtQVPs+BH68V63SPVA1wNxiDFKpH8bsael4W8h9TNARgiKawdDB4abo4eMicBAZIPUtFW0nO7CDwLj35XXWqbKTr1v7ufBDt6/2wp+j2sgsAUlcTu5idRyPZjOgK2dFE7f75RtyVevkquNsUMdK3O8Qo01sU0kj0oOhCHLkDlTFgAlKZ6hVe+MEtx19bcQSgp1j0LVcLi0fMkPESO0P0uRg2yqcNSQAO6Sd"
PANEL_ACCESS_KEY = "d6d0e1b39714d1304018c209bbf0e352d57b99ff6de02eac"
