name = "apk2source-api-v3"
main = "backend/worker.js"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[r2_buckets]]
bucket_name = "apk2source-uploads"
binding = "apk2source_uploads"

[vars]
APK2SOURCE_REPO = "vladleopold/apk2source"
APK2SOURCE_SPINE_REPO = "vladleopold/source_spine"
APK2SOURCE_SOURCE_REPO = "vladleopold/game_source"
PANEL_ACCESS_KEY = "d6d0e1b39714d1304018c209bbf0e352d57b99ff6de02eac"
