name = "apk2source-api-v3"
main = "backend/worker.js"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
APK2SOURCE_REPO = "vladleopold/apk2source"
APK2SOURCE_SPINE_REPO = "vladleopold/source_spine"
APK2SOURCE_SOURCE_REPO = "vladleopold/game_source"
GITHUB_TOKEN = "kgh2.WJ9spmjUzI30JHIABpwSLQ==:tQSPvURBKU451gj/nRNEYg==:D/lVV85DX4ErHjzr/N/gGdBXJMTfxyhgmwuOdrCtRFd5ujzisGLEcp6wt5Q6eb0XtNXBFQFMFZXgRD9OIQPwIkdsiPalvSs3MoqMFqocmUBIO4GNB5d42RbJLwNem1lmsaD74PmhrCUMx48WCBj/x4M/zGrYxatVrOx72FbHIj6p9CZqYIm0/xD0KPLQO8fidBFN/iIuB3xJJaPnRGCaEBI8SJ3y4FuVqxHjXFn2r/MDLDTFwV4TUD1FEb6V6JptbBa3SIxOa33enMyol3gnzWFxWKC1hjSbPHH899c3Qxo5yvVMtXt6Il9JkGkXUPijA3/J9db0+aYLlI/+oZHvz6FMga0zNGusZ1tohcolcffEHEkTGPDATOBr/924HHHuA5WdbXH+gvqwkgL2BiHu29ZMiPPj9R5MZwf12XFrErYL814mFOOejsF0gsB7ECAtZfy08TQ9zJYflKYFBW9I6Q2sXPnvIQ2A+7Whut2mKn4y4JjNRGfJb2gLYSybDKdhxDn+SGNL65HKkv+fxx/4IwexFdQGpHgENm1HzJLzQWYGKRCdiekrTYIQQ88T0SjxgNqM0GOzYZ9/SoKiALg9K6HbWdDdYf/WKlFmPrAKQFQZ80/uV7a9HWcUie6it6fccRHQhbfI3jj3Kt/t"
PANEL_ACCESS_KEY = "d6d0e1b39714d1304018c209bbf0e352d57b99ff6de02eac"
